//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/pcmac/PCMACMessage.msg.
//

#ifndef __PCMACMESSAGE_M_H
#define __PCMACMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class PCMACMessage;
// cplusplus {{
#include "veins/modules/messages/BaseFrame1609_4_m.h"
// }}

/**
 * Class generated from <tt>src/pcmac/PCMACMessage.msg:11</tt> by opp_msgtool.
 * <pre>
 * packet PCMACMessage extends veins::BaseFrame1609_4
 * {
 *     bool isEmergency = false;      // true = event msg, false = beacon
 *     double priority = 0.0;        // PCMAC priority (Equation 4)
 *     double senderX;                  // sender position at send time
 *     double senderY;
 *     double senderSpeed;              // m/s
 *     int platoonSize;              // N — received from RSU broadcast
 *     double platoonAvgVelocity;       // V — received from RSU broadcast
 *     int vehiclesBehind;           // count of trailing vehicles
 * }
 * </pre>
 */
class PCMACMessage : public ::veins::BaseFrame1609_4
{
  protected:
    bool isEmergency_ = false;
    double priority = 0.0;
    double senderX = 0;
    double senderY = 0;
    double senderSpeed = 0;
    int platoonSize = 0;
    double platoonAvgVelocity = 0;
    int vehiclesBehind = 0;

  private:
    void copy(const PCMACMessage& other);

  protected:
    bool operator==(const PCMACMessage&) = delete;

  public:
    PCMACMessage(const char *name=nullptr, short kind=0);
    PCMACMessage(const PCMACMessage& other);
    virtual ~PCMACMessage();
    PCMACMessage& operator=(const PCMACMessage& other);
    virtual PCMACMessage *dup() const override {return new PCMACMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool isEmergency() const;
    virtual void setIsEmergency(bool isEmergency);

    virtual double getPriority() const;
    virtual void setPriority(double priority);

    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);

    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);

    virtual double getSenderSpeed() const;
    virtual void setSenderSpeed(double senderSpeed);

    virtual int getPlatoonSize() const;
    virtual void setPlatoonSize(int platoonSize);

    virtual double getPlatoonAvgVelocity() const;
    virtual void setPlatoonAvgVelocity(double platoonAvgVelocity);

    virtual int getVehiclesBehind() const;
    virtual void setVehiclesBehind(int vehiclesBehind);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PCMACMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PCMACMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline PCMACMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<PCMACMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PCMACMESSAGE_M_H

